Repository jae-hun-e/LocoMoco, pull requests merged in 2024-10, with the labels that each got.

#207 [#205] 안드로이드 카카오 웹브라우저에서 지도 렌더 오류 해결
  src/hooks/useGeolocation.ts
Labels: Bug

#204 [#202] 네브바 스타일 및 마커 아이콘 변경
  public/chat.svg
  public/created-mgc-marker.png
  public/current-location-marker.png
  public/map.svg
  public/mypage.svg
  public/new-location-marker.png
  public/search-icon.svg
  public/search.svg
  src/app/(auth)/redirect/[method]/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(home)/_components/BottomSheet.tsx
  src/app/(home)/_components/HomeMapContent.tsx
  src/app/(home)/_components/HomeMapFooter .tsx
  src/app/_components/Map/ClustererProvider.tsx
  src/app/_components/Map/MapViewer.tsx
  src/app/_components/Map/Markers.tsx
  src/app/_components/NavBar.tsx
  src/app/_stories/Nanbar.stories.tsx
  src/app/chat/_components/ChatInput.tsx
  src/app/chat/_components/Messages.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/create/_components/CreateMGCMapContent.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_components/StaticMap.tsx
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/components/MainStyleButton.tsx
  src/components/ui/toaster.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Style, Modify

#210 [#206] A2HS
  public/manifest.json
  src/app/(home)/page.tsx
  src/app/_components/A2HS.tsx
  src/app/_components/CreateBtn.tsx
  src/app/chat/[mgcId]/page.tsx
  src/app/layout.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/app/mypage/loading.tsx
  src/hooks/useA2HS.tsx
Labels: Feat

#209 [#208] 지도페이지의 지도 롱프레스시 바텀시트 나타나도록 변경
  public/create-position-marker.png
  public/location-pin.svg
  src/app/(home)/_components/BottomSheet.tsx
  src/app/(home)/_components/HomeMapContent.tsx
  src/app/(home)/_components/HomeMapViewer.tsx
  src/app/(home)/_components/MGCCreateBottomSheet.tsx
  src/app/(home)/_components/MGCCreateSheetContent.tsx
  src/app/(home)/_stories/MGCCreateBottomSheet.stories.tsx
  src/app/_components/Map/Marker.tsx
  src/components/ui/drawer.tsx
  src/components/ui/sheet.tsx
  src/hooks/useChangeMapCenter.ts
Labels: Refactor, Style

#213 [#203] 지도 및 검색 페이지에서 공통 SearchBarFilter 컴포넌트 적용 및 디자인 개선
  public/arrow-down.svg
  public/category.svg
  public/reading-glasses.svg
  src/apis/mgcList/useMGCTotalList.ts
  src/app/(home)/_components/CategoryFilter.tsx
  src/app/(home)/_components/FilterContent.tsx
  src/app/(home)/_components/HomeMapContent.tsx
  src/app/(home)/_components/HomeMapViewer.tsx
  src/app/(home)/_components/HomeSearchBarFilter.tsx
  src/app/(home)/_components/MapSection.tsx
  src/app/(home)/_components/SearchBar.tsx
  src/app/(home)/_components/SearchBarFilter.tsx
  src/app/(home)/_stories/SearchBarFilter.stories.tsx
  src/app/(home)/page.tsx
  src/app/_components/Map/MGCMap.tsx
  src/app/_components/Map/MapViewer.tsx
  src/app/_components/SearchBar.tsx
  src/app/_components/SearchBarFilter.tsx
  src/app/_components/SearchBarFilter/CategoryDetailBtn.tsx
  src/app/_components/SearchBarFilter/CategoryDetailBtnGroup.tsx
  src/app/_components/SearchBarFilter/CategoryFilterSection.tsx
  src/app/_components/SearchBarFilter/CategorySelectBtn.tsx
  src/app/_components/SearchBarFilter/CategorySelectBtnGroup.tsx
  src/app/_components/SearchBarFilter/SubmitResetGroup.tsx
  src/app/_components/Tag.tsx
  src/app/_stories/SearchBar.stories.tsx
  src/app/_stories/SearchBarFilter.stories.tsx
  src/app/create/_components/CreateMGCMapViewer.tsx
  src/app/search/_components/SearchBarFilter.tsx
  src/app/search/page.tsx
  src/app/sitemap.ts
  src/constants/categoryFilter.ts
  src/hooks/useCategoryList.ts
  src/store/useSearchValueStore.ts
  src/tests/CategoryFilterSection.spec.tsx
  src/tests/Home.spec.tsx
  src/tests/SearchBarFilter.spec.tsx
  src/types/searchFilterCategory.ts
  tailwind.config.ts
Labels: Feat, Refactor, Style, Remove

#217 [#216] app icon
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
Labels: Fix

#215 [#214] 검색 페이지 모달 문제 및 마커 중복 렌더링, 바텀시트 버튼 이슈 해결
  src/app/_components/CreateBtn.tsx
  src/app/_components/MGCList/MGCList.tsx
  src/app/_components/Map/Markers.tsx
  src/app/search/page.tsx
Labels: Bug
