Repository jae-hun-e/LocoMoco, pull requests merged in 2024-03, with the labels that each got.

#43 [#31] 홈페이지 api 연결 및 디자인된 컴포넌트로 변경
  package.json
  src/apis/core.ts
  src/apis/mgc/queryFn.ts
  src/apis/mgcList/queryFn.ts
  src/apis/mgcList/useMGCList.ts
  src/app/(home)/_components/BottomSheet.tsx
  src/app/(home)/_components/Map.tsx
  src/app/(home)/_components/MapSection.tsx
  src/app/(home)/_components/SearchBarFilter.tsx
  src/app/(home)/page.tsx
  src/app/_components/MGCList/MGCList.tsx
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/_components/MapCustomControl.tsx
  src/app/_components/filter/Filter.tsx
  src/app/_components/filter/FilterContent.tsx
  src/app/_components/filter/TypeCheckList.tsx
  src/app/search/page.tsx
  src/components/ui/drawer.tsx
  src/constants/mgcListDummy.ts
  src/hooks/useCreateKakaoMap.ts
  src/hooks/useGeolocation.ts
  src/hooks/useKakaoMap.ts
  src/hooks/useRenderMarkerByData.ts
  src/store/useCenterPosition.ts
  src/store/useMapMGCDataStore.ts
  src/styles/globals.css
  src/types/MGCList.ts
  src/types/searchFilterForm.ts
  src/utils/getQueryOptions.ts
  yarn.lock
Labels: Feat, Refactor, Modify

#49 [48] 번개 모각코 API 연결
  src/apis/mgc/queryFn.ts
  src/apis/thunderMGC/useCreateThunderMGC.ts
  src/app/(home)/_components/ThunderModal/LocationSearch.tsx
  src/app/(home)/_components/ThunderModal/ThunderModal.tsx
  src/app/_components/CreateBtn.tsx
Labels: Feat

#50 [#47] kakao map 클릭 이벤트 관련 버그 및 오류 해결
  src/app/(home)/_components/Map.tsx
  src/app/(home)/_components/MapSection.tsx
  src/hooks/useCreateKakaoMap.ts
  src/hooks/useRenderMarkerByData.ts
Labels: Bug, Modify

#51 [#41] mgc detail api 연결
  .gitignore
  src/apis/mgc/queryFn.ts
  src/apis/mgc/useGetMGCDetail.tsx
  src/app/create/_components/MGCDate.tsx
  src/app/mgc/[id]/_components/AuthorInfo.tsx
  src/app/mgc/[id]/_components/Inquiry.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_components/MGCInfo.tsx
  src/app/mgc/[id]/_components/MGCOptions.tsx
  src/app/mgc/[id]/_components/MGCParticipants.tsx
  src/app/mgc/[id]/_components/StaticMap.tsx
  src/app/mgc/[id]/page.tsx
  src/constants/mgcDummyData.ts
  src/utils/filterTagByIds.ts
  src/utils/getQueryOptions.tsx
Labels: Feat, Modify

#59 [#58] 서버에서 localStorage 접근으로 인해 에러 발생
  src/apis/core.ts
Labels: Bug

#65 [#64] 조회수 중복 증가 및 server client 데이터 불일치 에러 임시 해결
  src/apis/mgc/useGetMGCDetail.ts
  src/app/_components/Provider.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/page.tsx
Labels: Bug

#54 [#44] 후기 생성 api 연결
  src/apis/review/useCreateReview.ts
  src/apis/user/useGetUserInfo.ts
  src/app/chat/_components/review/Review.tsx
  src/app/chat/_components/review/ReviewContent.tsx
  src/constants/userInfo.ts
  src/utils/storage.ts
Labels: Feat

#60 [#57] 마이페이지 블랙리스트 UI
  src/app/_components/UserInfoAndButton/UserList.tsx
  src/app/_components/UserInfoAndButton/UserListItem.tsx
  src/app/chat/[id]/participants/page.tsx
  src/app/mypage/black-list/page.tsx
Labels: Feat

#62 [#55] 받은 리뷰 평가 페이지 구현
  src/apis/review/useGetReceivedReviews.ts
  src/apis/review/useGetReviewContents.ts
  src/app/_components/header/HeaderLeft.tsx
  src/app/mypage/page.tsx
  src/app/mypage/received-reviews-assessment/_components/ReviewList.tsx
  src/app/mypage/received-reviews-assessment/layout.tsx
  src/app/mypage/received-reviews-assessment/page.tsx
  src/app/mypage/received-reviews/page.tsx
  src/app/mypage/send-reviews/page.tsx
  src/constants/routeURL.ts
  tsconfig.json
Labels: Feat

#71 [#61] 마이페이지 신고목록 UI 구현
  src/app/mypage/report-list/_components/ReportList.tsx
  src/app/mypage/report-list/_components/ReportListItem.tsx
  src/app/mypage/report-list/page.tsx
Labels: Feat

#67 [#63] 보낸리뷰, 받은리뷰 페이지 ui 구현
  src/app/_components/reviewList/ReviewDetail.tsx
  src/app/_components/reviewList/ReviewItem.tsx
  src/app/_components/reviewList/ReviewList.tsx
  src/app/_components/reviewList/UserInfo.tsx
  src/app/chat/_components/review/StarList.tsx
  src/app/mypage/end-join-mgc/received-reviews/page.tsx
  src/app/mypage/end-join-mgc/send-reviews/page.tsx
  src/types/review.ts
  tailwind.config.ts
Labels: Feat, Style

#53 [#52] 마이페이지 내부 모각코관련 세부페이지 UI 구현
  src/app/_components/header/HeaderLeft.tsx
  src/app/mypage/(sub-page)/_components/MGCSummaryInfo.tsx
  src/app/mypage/(sub-page)/_components/button/ChattingButton.tsx
  src/app/mypage/(sub-page)/_components/button/LikeMGCAreaButtons.tsx
  src/app/mypage/(sub-page)/_components/button/ReviewButtons.tsx
  src/app/mypage/(sub-page)/current-join-mgc/page.tsx
  src/app/mypage/(sub-page)/end-join-mgc/page.tsx
  src/app/mypage/(sub-page)/layout.tsx
  src/app/mypage/(sub-page)/like-mgc/page.tsx
  src/app/mypage/current-join-mgc/page.tsx
  src/app/mypage/end-join-mgc/page.tsx
  src/app/mypage/like-mgc/page.tsx
  src/constants/routeURL.ts
Labels: Feat, Style

#69 [#68] 로그인/회원가입 로직 변경
  src/apis/core.ts
  src/app/(auth)/redirect/[method]/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/[method]/page.tsx
  src/app/(auth)/signup/_components/DatePick.tsx
  src/app/(auth)/signup/_components/ProgressBar.tsx
  src/app/_components/Modal.tsx
  src/utils/storage.ts
Labels: Feat, Fix, Refactor

#66 [#39] 채팅 기능 만들기
  src/apis/chat/queryFn.ts
  src/apis/chat/useChatList.ts
  src/apis/core.ts
  src/app/_components/header/HeaderLeft.tsx
  src/app/chat/[id]/page.tsx
  src/app/chat/_components/ChatInput.tsx
  src/app/chat/_components/Message.tsx
  src/app/chat/_components/Messages.tsx
  src/app/chat/page.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  yarn.lock
Labels: Feat, Fix, Refactor

#72 [#70] 홈페이지 동명검색 및 필터 사용자 입력 적용
  src/apis/core.ts
  src/apis/mgcList/useMGCTotalList.ts
  src/app/(home)/_components/MapSection.tsx
  src/app/(home)/page.tsx
  src/app/_components/filter/Filter.tsx
  src/app/_components/filter/FilterContent.tsx
  src/app/_components/filter/TypeCheckList.tsx
  src/app/layout.tsx
  src/hooks/useCreateKakaoMap.ts
  src/store/useSearchValueStore.ts
Labels: Modify

#77 [#73] 마이페이지 블랙리스트 API 연결
  src/apis/blacklist/useDeleteBlacklist.ts
  src/apis/blacklist/useGetBlacklist.ts
  src/app/_components/UserInfoAndButton/UserList.tsx
  src/app/_components/UserInfoAndButton/UserListItem.tsx
  src/app/chat/[id]/participants/page.tsx
  src/app/mypage/black-list/page.tsx
Labels: Feat

#85 [#81 ] 모각코 디테일 페이지에 참여하기와 톡방 연결
  src/apis/mgc/useGetMGCDetail.ts
  src/app/_components/header/HeaderLeft.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_hooks/useApplyMGC.ts
  src/app/mgc/[id]/_hooks/useIsApply.ts
  src/components/MainStyleButton.tsx
  src/constants/routeURL.ts
  src/hooks/useCreateKakaoMap.ts
  src/utils/getQueryOptions.tsx
Labels: Feat, Modify

#91 [#89 ] 마이페이지 내 모각코페이지들 API연결
  src/app/mypage/(sub-page)/_components/button/LikeMGCAreaButtons.tsx
  src/app/mypage/(sub-page)/current-join-mgc/_hooks/useGetCurrentJoinMGC.ts
  src/app/mypage/(sub-page)/current-join-mgc/page.tsx
  src/app/mypage/(sub-page)/end-join-mgc/_hooks/useGetEndMGC.ts
  src/app/mypage/(sub-page)/end-join-mgc/page.tsx
  src/app/mypage/(sub-page)/like-mgc/_hooks/useGetLikeMGC.ts
  src/app/mypage/(sub-page)/like-mgc/page.tsx
  src/app/mypage/_components/UserInfo.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/app/mypage/page.tsx
Labels: Feat

#93 [#79] 마이페이지 신고 목록 API 연결
  src/apis/report/useDeleteReportList.ts
  src/apis/report/useGetReportList.ts
  src/apis/report/useModifyReportList.ts
  src/app/mypage/report-list/_components/ReportList.tsx
  src/app/mypage/report-list/_components/ReportListItem.tsx
  src/app/mypage/report-list/_components/ReportModifyModal.tsx
  src/app/mypage/report-list/page.tsx
  src/types/report.ts
Labels: Feat

#96 [#78] 검색페이지 필터 연결 및 태그 정보 연결
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/search/page.tsx
Labels: Feat

#98 [#82] 로그아웃/회원탈퇴
  src/app/(auth)/signup/[method]/page.tsx
  src/app/(auth)/signup/_components/DatePick.tsx
  src/app/(auth)/signup/_components/Gender.tsx
  src/app/(auth)/signup/_components/Job.tsx
  src/app/(auth)/signup/_components/Nickname.tsx
  src/app/mypage/(sub-page)/change-my-info/page.tsx
  src/app/mypage/page.tsx
  src/types/userInfo.ts
Labels: Feat, Refactor

#102 [#87] 다른 유저 상세 페이지 api 연결
  src/apis/review/useGetReceivedReviewSummary.ts
  src/apis/review/useGetSentReviewSummary.ts
  src/apis/user/queryFn.ts
  src/apis/user/useGetJoinMGCByUserId.ts
  src/apis/user/useGetUserInfo.ts
  src/app/_components/MGCList/MGCList.tsx
  src/app/_components/UserProfileInfo.tsx
  src/app/another/[userId]/(main)/page.tsx
  src/app/another/[userId]/join-mgc/page.tsx
  src/app/chat/[id]/loading.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/mypage/page.tsx
  src/constants/mypageDummyData.ts
Labels: Feat

#103 [#101] 모각코별 다른 채팅방 들어가기
  src/app/chat/[id]/page.tsx
  src/app/chat/_components/Message.tsx
  src/app/chat/_components/Messages.tsx
  src/app/chat/_components/NotMessage.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
Labels: Fix

#105 [#94] 채팅 페이지 내 참여 목록 및 후기 작성을 위한 모달 기능 추가
  src/apis/review/useCreateReview.ts
  src/app/_components/Modal.tsx
  src/app/_components/header/Header.tsx
  src/app/_components/header/MenuBtn.tsx
  src/app/chat/[id]/page.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/chat/layout.tsx
Labels: Feat, Modify

#99 [#95] 모각코 생성 페이지 변경 및 수정페이지 구현
  src/apis/mgc/queryFn.ts
  src/apis/mgc/useCreateMGC.ts
  src/apis/mgc/useGetMGCDetail.ts
  src/app/create/_components/CheckboxGroup.tsx
  src/app/create/_components/CreateMGC.tsx
  src/app/create/_components/DatePick.tsx
  src/app/create/_components/MGCDate.tsx
  src/app/create/_components/MGCMap.tsx
  src/app/create/_components/MGCTime.tsx
  src/app/create/_components/OptionFields.tsx
  src/app/create/_components/RequiredFields.tsx
  src/app/create/page.tsx
  src/app/edit-mgc/[id]/error.tsx
  src/app/edit-mgc/[id]/layout.tsx
  src/app/edit-mgc/[id]/loading.tsx
  src/app/edit-mgc/[id]/page.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_components/MGCOptions.tsx
  src/constants/routeURL.ts
  src/hooks/useFilterTagByIds.ts
  src/hooks/useTagMapping.ts
  src/utils/filterTagByIds.ts
  src/utils/getTimeString.ts
Labels: Feat, Modify

#106 [#46] PWA 세팅 + 웹푸시알림(FCM) 구현
  next.config.mjs
  package.json
  public/firebase-messaging-sw.js
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/manifest.json
  public/next.svg
  public/splashscreens/ipad_splash.png
  public/splashscreens/ipadpro1_splash.png
  public/splashscreens/ipadpro2_splash.png
  public/splashscreens/ipadpro3_splash.png
  public/splashscreens/iphone5_splash.png
  public/splashscreens/iphone6_splash.png
  public/splashscreens/iphoneplus_splash.png
  public/splashscreens/iphonex_splash.png
  public/splashscreens/iphonexr_splash.png
  public/splashscreens/iphonexsmax_splash.png
  public/vercel.svg
  src/apis/core.ts
  src/apis/mgc/useGetMGCDetail.ts
  src/apis/mgc/usePatchMGC.ts
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/_components/Provider.tsx
  src/app/api/db/route.ts
  src/app/api/fcm/route.ts
  src/app/api/fcm/sendFCM.ts
  src/app/create/_components/CreateMGC.tsx
  src/app/edit-mgc/[id]/page.tsx
  src/app/favicon.ico
  src/app/fcm/_components/FCMPermission.tsx
  src/app/fcm/_components/FCMPush.tsx
  src/app/fcm/_hooks/useSaveTokenToDB.ts
  src/app/fcm/_hooks/useSendPush.ts
  src/app/fcm/page.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/_components/MGCOptions.tsx
  src/app/mypage/(sub-page)/_components/MGCSummaryInfo.tsx
  src/app/mypage/(sub-page)/change-my-info/page.tsx
  src/app/mypage/(sub-page)/current-join-mgc/page.tsx
  src/app/mypage/(sub-page)/end-join-mgc/page.tsx
  src/app/mypage/(sub-page)/like-mgc/page.tsx
  src/app/mypage/_components/UserInfo.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/app/mypage/page.tsx
  src/hooks/useFilterTagByIds.ts
  src/hooks/useKakaoMap.ts
  src/hooks/useTagMapping.ts
  src/libs/database.ts
  src/utils/getDeviceType.ts
  src/utils/getQueryOptions.tsx
  yarn.lock
Labels: Feat, Chore, Modify

#110 [#97] 모각코 리스트에 모각코 생성 시간 및 수정 시간 추가
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/search/page.tsx
  src/constants/mgcListDummy.ts
  src/types/MGCList.ts
Labels: Feat

#109 [#104] 채팅방/로그인 마무리
  src/apis/chat/queryFn.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/[method]/page.tsx
  src/app/(auth)/signup/_components/Job.tsx
  src/app/chat/[mgcId]/loading.tsx
  src/app/chat/[mgcId]/page.tsx
  src/app/chat/[mgcId]/participants/page.tsx
  src/app/chat/_components/Message.tsx
  src/app/chat/_components/Messages.tsx
  src/app/chat/page.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mypage/(sub-page)/change-my-info/page.tsx
  src/types/chat.ts
  src/types/userInfo.ts
Labels: Fix

#107 [#100] 개인정보 수정 구현 + QA 수정사항 반영
  src/app/create/_components/OptionFields.tsx
  src/app/mypage/(sub-page)/change-my-info/_hooks/useChangeMyInfo.ts
  src/app/mypage/(sub-page)/change-my-info/page.tsx
  src/app/mypage/_components/UserInfo.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/types/userInfo.ts
Labels: Feat, Modify

#112 [#111] 비회원 처리 + 외부 이미지 설정 추가
  next.config.mjs
  src/app/_components/header/Header.tsx
  src/app/_components/header/HeaderLeft.tsx
  src/app/mgc/[id]/_components/Inquiry.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mypage/page.tsx
  src/constants/routeURL.ts
Labels: Bug, Feat, Style

#117 [#116] 번개 모각코 tag 추가 및 생성 시 디테일 페이지로 이동
  src/apis/thunderMGC/useCreateThunderMGC.ts
  src/app/(home)/_components/ThunderModal/ThunderModal.tsx
Labels: Fix

#118 [#115] 마이페이지 내 모각코들 로직 구현
  src/app/_components/header/Header.tsx
  src/app/create/_components/CreateMGC.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mypage/(sub-page)/_components/button/ChattingButton.tsx
  src/app/mypage/(sub-page)/_components/button/ReviewButtons.tsx
  src/app/mypage/(sub-page)/change-my-info/page.tsx
  src/app/mypage/(sub-page)/end-join-mgc/received-reviews/[mgcId]/page.tsx
  src/app/mypage/(sub-page)/end-join-mgc/send-reviews/[mgcId]/page.tsx
  src/app/mypage/_components/UserInfo.tsx
  src/app/mypage/logout/page.tsx
  src/constants/routeURL.ts
Labels: Feat, Fix

#123 [#88] 롱클릭시 모각코 생성 위치 표시를 마커에서 인포윈도우로 변경
  src/app/(home)/_components/Map.tsx
  src/app/(home)/_components/MapSection.tsx
  src/app/_components/infoWindow/InfoWindow.tsx
  src/store/useCreatedPositionInfo.ts
  src/store/useInfoWindowPosition.ts
  src/styles/globals.css
Labels: Feat, Refactor

#127 [#124] 일반 모각코 생성 시 롱클릭시 모각코 생성 위치 표시
  src/app/create/_components/CreateMGC.tsx
Labels: Feat

#126 [#119] 로그인 하지 않은 사용자에 대한 대응
  src/app/(auth)/redirect/[method]/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/_components/CreateBtn.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/UserInfoAndButton/UserList.tsx
  src/app/_components/UserInfoAndButton/UserListItem.tsx
  src/app/chat/[mgcId]/page.tsx
  src/app/chat/_components/ChatInput.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/chat/page.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/app/mypage/page.tsx
  src/components/ProgressBar.tsx
Labels: Fix, Modify

#128 [#120] 번개 모각코 생성 페이지 QA 반영
  src/app/(home)/_components/ThunderModal/MGCMap.tsx
  src/app/(home)/_components/ThunderModal/ThunderModal.tsx
  src/app/(home)/_components/ThunderModal/ThunderModalContent.tsx
Labels: Feat, Fix

#129 [#121] 블랙리스트 신고페이지 QA 수정사항 반영
  src/apis/mgc/useGetMGCDetail.ts
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/AuthorInfo.tsx
  src/app/mypage/(sub-page)/black-list/page.tsx
  src/app/mypage/(sub-page)/report-list/_components/ReportList.tsx
  src/app/mypage/(sub-page)/report-list/_components/ReportListItem.tsx
  src/app/mypage/(sub-page)/report-list/_components/ReportModifyModal.tsx
  src/app/mypage/(sub-page)/report-list/page.tsx
  src/constants/routeURL.ts
Labels: Feat, Fix

#131 [#130] 시간 표시 오류
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/chat/_components/Message.tsx
  src/app/mypage/page.tsx
Labels: Fix

#133 [#132] 모각코 디테일 qa반영
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mypage/(sub-page)/change-my-info/page.tsx
Labels: Bug, Feat

#134 [#125] 모각코 헤더 버튼 클릭 시 신고 삭제 기능
  src/apis/mgc/useDeleteMGC.ts
  src/apis/report/useCreateReport.ts
  src/app/_components/ReportForm.tsx
  src/app/_components/header/Header.tsx
  src/app/_components/header/OptionBtn.tsx
  src/app/_components/header/ShareBtn.tsx
  src/app/another/[userId]/(main)/layout.tsx
  src/app/another/[userId]/(main)/page.tsx
  src/app/another/[userId]/_components/HeaderOptionContent.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/HeaderOptionContent.tsx
  src/app/mgc/[id]/_components/ReportCreateModal.tsx
  src/app/mgc/layout.tsx
  src/app/mypage/(sub-page)/report-list/_components/ReportModifyModal.tsx
  src/store/useMGCCreateUserId.ts
Labels: Feat, Refactor

#139 fix: token allocation
  src/app/_components/CreateBtn.tsx
Labels: Fix

#140 [#135] pwa config 오류 수정
  next.config.mjs
Labels: Feat

#144 [#143] 보낸 리뷰페이지의 후기 프로필 리뷰 받은 사람의 프로필로 변경
  src/apis/review/useGetSentReviewSummary.ts
Labels: Modify

#147 [#146] 필터 카테고리 중 "전체" 카테고리 제거
  src/app/_components/filter/FilterContent.tsx
  src/app/_components/filter/TypeCheckList.tsx
Labels: Modify

#149 [#148] 더미데이터값 실제값으로 변경
  src/app/chat/_components/review/ReviewContent.tsx
  src/app/mypage/received-reviews-assessment/page.tsx
Labels: Modify
