Repository jae-hun-e/LocoMoco, pull requests merged in 2024-12, with the labels that each got.

#212 [#211] Error page
  public/error.png
  src/app/error.tsx
Labels: Feat

#227 [#226] 중복 지도 로드를 방지하도록 isLoad 조건 추가
  src/app/_components/Map/MapLoaderProvider.tsx
Labels: Fix

#229 [#173] 사용하지 않는 파일 제거
  src/app/(home)/_components/Map.tsx
  src/app/(home)/_components/MapSection.tsx
  src/app/_components/Radio.tsx
  src/app/_components/RadioGroup.tsx
  src/app/_components/filter/Filter.tsx
  src/app/_components/filter/FilterContent.tsx
  src/app/_components/filter/TypeCheckList.tsx
  src/constants/metroGovernments.ts
  src/constants/mgcDummyData.ts
  src/constants/mypageDummyData.ts
  src/hooks/useCreateKakaoMap.ts
  src/hooks/useKakaoMap.ts
  src/hooks/useRenderMarkerByData.ts
  src/store/useCenterPosition.ts
  src/store/useMapMGCDataStore.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/types/MGCSummary.ts
  src/types/searchFilterForm.ts
  src/utils/getQueryOptions.tsx
Labels: Remove
