Repository jae-hun-e/LocoMoco, pull requests merged in 2024-04, with the labels that each got.

#150 [#137] 유저 페이지 연결 및 존재하지 않는 유저 처리
  src/apis/review/useGetReceivedReviewSummary.ts
  src/apis/review/useGetSentReviewSummary.ts
  src/apis/user/useGetUserInfo.ts
  src/app/_components/ProfileImg.tsx
  src/app/_components/UserInfoAndButton/UserListItem.tsx
  src/app/_components/UserProfileInfo.tsx
  src/app/_components/reviewList/ReviewItem.tsx
  src/app/_components/reviewList/UserInfo.tsx
  src/app/another/[userId]/(main)/error.tsx
  src/app/another/[userId]/(main)/loading.tsx
  src/app/another/[userId]/(main)/page.tsx
  src/app/chat/_components/Message.tsx
  src/app/chat/_components/review/Profile.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/mgc/[id]/_components/AuthorInfo.tsx
  src/app/mgc/[id]/_components/MGCParticipants.tsx
  src/constants/mypageDummyData.ts
  src/types/review.ts
Labels: Feat, Modify

#157 [#156] 모바일에서 인포윈도우 닫을 시 닫힘 버튼 위치로 이동되는 문제 해결
  src/app/(home)/_components/Map.tsx
Labels: Bug

#158 [#154] 모바일에서 지도 롱프레스시 SVG 요소가 선택되는 문제 해결
  src/app/(home)/_components/Map.tsx
  src/styles/globals.css
Labels: Bug

#162 [#161] 모각코 수정시 리스트에서 사라지는 문제 해결
  src/app/create/_components/CreateMGC.tsx
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
Labels: Bug, Fix

#160 [#159] 로그인을 하지 않은 유저에 대한 예외처리
  next.config.mjs
  src/app/_components/Provider.tsx
  src/app/mypage/_components/UserInfo.tsx
  src/app/mypage/_hooks/useMypageInfo.ts
  src/app/mypage/page.tsx
Labels: Bug, Fix

#153 [#152] SEO 유지 및 소셜 미디어 최적화
  src/apis/mgc/useGetMGCDetail.ts
  src/apis/mgcList/useMGCTotalList.ts
  src/app/chat/[mgcId]/layout.tsx
  src/app/chat/layout.tsx
  src/app/create/layout.tsx
  src/app/edit-mgc/[id]/EditPage.tsx
  src/app/edit-mgc/[id]/page.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/page.tsx
  src/app/mypage/layout.tsx
  src/app/opengraph-image.png
  src/app/robots.ts
  src/app/search/layout.tsx
  src/app/sitemap.ts
  src/constants/mgcListDummy.ts
  src/constants/routeURL.ts
  src/types/MGCList.ts
Labels: Feat, Chore
