Repository jae-hun-e/LocoMoco, pull requests merged in 2024-02, with the labels that each got.

#2 [#1]navbar추가
  commitlint.config.js
  src/app/(isHeader)/chat/page.tsx
  src/app/(isHeader)/create/page.tsx
  src/app/(isHeader)/layout.tsx
  src/app/(isHeader)/mgc/[id]/page.tsx
  src/app/(isHeader)/mypage/page.tsx
  src/app/_components/Header.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/ThemeToggle.tsx
  src/app/chat/page.tsx
  src/app/create/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/page.tsx
  src/app/mypage/page.tsx
  src/constants/routeURL.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: Feat

#8 [#7] 데이터 패칭 core + 상태관리 세팅
  .eslintrc.json
  package.json
  src/apis/core.ts
  src/apis/mgc/queryFn.ts
  src/apis/mgc/useMGCDetail.ts
  src/app/_components/Provider.tsx
  src/app/_components/ThemeToggle.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/_components/MGCDetail.tsx
  src/app/mgc/[id]/error.tsx
  src/app/mgc/[id]/loading.tsx
  src/app/mgc/[id]/page.tsx
  src/app/mypage/page.tsx
  yarn.lock
Labels: Feat, Chore

#9 [#3] 모각코 디테일 페이지 UI 작업
  .gitignore
  .husky/commit-msg
  commitlint.config.js
  public/oh.png
  src/app/layout.tsx
  src/app/mgc/[id]/page.tsx
  src/constants/types.ts
  tailwind.config.ts
Labels: Chore, Style

#12 [#4] Signin/Signup 페이지 제작
  public/github.svg
  public/kakao.svg
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/_components/DatePick.tsx
  src/app/(auth)/signup/_components/Gender.tsx
  src/app/(auth)/signup/_components/Job.tsx
  src/app/(auth)/signup/_components/Nickname.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_components/Radio.tsx
  src/app/_components/RadioGroup.tsx
  src/app/layout.tsx
  src/hooks/useClickaway.ts
Labels: Feat, Fix, Chore

#13 [#5] 홈페이지 UI 구현
  commitlint.config.js
  package.json
  src/app/(home)/_components/BottomSheet.tsx
  src/app/(home)/page.tsx
  src/app/_components/CreateBtn.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/filter/Filter.tsx
  src/app/_components/filter/FilterContent.tsx
  src/app/_components/filter/TypeCheckList.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/sheet.tsx
  src/styles/globals.css
  src/types/searchFilterForm.ts
  tsconfig.json
  yarn.lock
Labels: Feat, Style

#17 [#11] header 구현
  src/app/_components/Header.tsx
  src/app/_components/header/Header.tsx
  src/app/_components/header/HeaderLeft.tsx
  src/app/chat/layout.tsx
  src/app/create/layout.tsx
  src/app/mgc/layout.tsx
  src/constants/routeURL.ts
Labels: Feat

#15 [#6] Search Page UI 구현
  src/app/_components/MGCList/MGCList.tsx
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/_components/Tag.tsx
  src/app/search/page.tsx
Labels: Feat

#24 [#10] 모각코 생성 페이지 구현
  src/app/_components/Tag.tsx
  src/app/_components/header/Header.tsx
  src/app/create/_components/CheckboxGroup.tsx
  src/app/create/_components/Combobox.tsx
  src/app/create/_components/DatePick.tsx
  src/app/create/_components/MGCDate.tsx
  src/app/create/_components/MGCTime.tsx
  src/app/create/_components/OptionFields.tsx
  src/app/create/_components/RequiredFields.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/_components/AuthorInfo.tsx
  src/app/mgc/[id]/_components/Inquiry.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_components/MGCDetail.tsx
  src/app/mgc/[id]/_components/MGCInfo.tsx
  src/app/mgc/[id]/_components/MGCParticipants.tsx
  src/app/mgc/[id]/page.tsx
  src/components/MainStyleButton.tsx
  src/components/ui/label.tsx
  src/constants/mgcDummyData.ts
  tailwind.config.ts
Labels: Feat, Modify

#25 [#14] 더미데이터로 지도 기능 구현
  src/apis/address/queryFn.ts
  src/apis/address/useAddressSearch.ts
  src/app/(home)/_components/AddressList.tsx
  src/app/(home)/_components/BottomSheet.tsx
  src/app/(home)/_components/Map.tsx
  src/app/(home)/_components/SearchBarFilter.tsx
  src/app/(home)/page.tsx
  src/app/_components/MGCList/MGCListItem.tsx
  src/app/_components/filter/Filter.tsx
  src/app/layout.tsx
  src/app/mgc/[id]/_components/MGCInfo.tsx
  src/components/ui/toaster.tsx
  src/constants/mgcDummyData.ts
  src/constants/types.ts
  src/hooks/useClickaway.ts
  src/hooks/useKakaoMap.ts
  src/store/useMapMGCDataStore.ts
  src/types/MGCSummary.ts
Labels: Feat, Modify

#32 [#26] 후기 모달 UI
  src/app/chat/_components/review/Profile.tsx
  src/app/chat/_components/review/Rating.tsx
  src/app/chat/_components/review/Review.tsx
  src/app/chat/_components/review/ReviewContent.tsx
  src/app/chat/_components/review/StarList.tsx
Labels: Feat, Style

#37 [#19] Modal 공통 컴포넌트 구현 및 번개 모각코 Modal UI 구현
  src/app/(home)/_components/ThunderModal/LocationSearch.tsx
  src/app/(home)/_components/ThunderModal/ThunderModal.tsx
  src/app/_components/Modal.tsx
  src/store/thunderModalStore.ts
Labels: Feat

#40 [#27] 모각코 생성 API 연결 및 카태고리 정보 프리패칭
  src/apis/core.ts
  src/apis/mgc/queryFn.ts
  src/apis/mgc/useCreateMGC.ts
  src/apis/mgc/useMGCDetail.ts
  src/app/_components/Provider.tsx
  src/app/create/_components/CheckboxGroup.tsx
  src/app/create/_components/Combobox.tsx
  src/app/create/_components/MGCTime.tsx
  src/app/create/_components/OptionFields.tsx
  src/app/create/_components/RequiredFields.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/utils/getQueryOptions.tsx
  src/utils/toKoreanTimeZone.ts
Labels: Feat, Modify

#34 [#20] Login api 연결 및 유효성 검사
  next.config.mjs
  package.json
  public/github.svg
  public/kakao.svg
  src/apis/core.ts
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/[method]/page.tsx
  src/app/(auth)/signup/_components/DatePick.tsx
  src/app/(auth)/signup/_components/Gender.tsx
  src/app/(auth)/signup/_components/Job.tsx
  src/app/(auth)/signup/_components/Nickname.tsx
  src/app/(auth)/signup/_components/ProgressBar.tsx
  src/app/(auth)/signup/_components/Warning.tsx
  src/app/(auth)/signup/page.tsx
  yarn.lock
Labels: Feat, Fix, Chore

#36 [#35] 채팅방 UI 제작
  src/app/chat/[id]/page.tsx
  src/app/chat/[id]/participants/page.tsx
Labels: Feat
