Repository jae-hun-e/LocoMoco, pull requests merged in 2024-05, with the labels that each got.

#164 [#163] 지도 커스텀훅 커스텀화 리팩토링
  src/app/(home)/_components/HomeMap.tsx
  src/app/(home)/_components/HomeMapViewer.tsx
  src/app/(home)/_components/MapSection.tsx
  src/app/(home)/_components/SearchBarFilter.tsx
  src/app/(home)/page.tsx
  src/app/_components/Map/Clusterer.tsx
  src/app/_components/Map/Geocoder.tsx
  src/app/_components/Map/Map.tsx
  src/app/_components/Map/MapProvider.tsx
  src/app/_components/Map/MapViewer.tsx
  src/app/_components/Map/Marker.tsx
  src/app/_components/Map/Markers.tsx
  src/app/_components/infoWindow/InfoWindow.tsx
  src/app/layout.tsx
  src/hooks/useChangeMapCenter.ts
  src/hooks/useGetAddressByCoordinates.ts
  src/store/useKakaoMapLoad.ts
  src/store/useSearchValueStore.ts
Labels: Feat, Refactor

#151 Feat/#42/mgc detail like and inquiry
  src/apis/mgc/usePatchMGC.ts
  src/app/mgc/[id]/MGCPage.tsx
  src/app/mgc/[id]/_components/Inquiry.tsx
  src/app/mgc/[id]/_components/MGCApplyArea.tsx
  src/app/mgc/[id]/_components/inquiry/Inquiry.tsx
  src/app/mgc/[id]/_components/inquiry/InquiryContainer.tsx
  src/app/mgc/[id]/_components/inquiry/InquiryForm.tsx
  src/app/mgc/[id]/_components/inquiry/InquiryTooltip.tsx
  src/app/mgc/[id]/_hooks/useApplyMGC.ts
  src/app/mgc/[id]/_hooks/useCreateInquiry.ts
  src/app/mgc/[id]/_hooks/useDeleteInquiry.ts
  src/app/mgc/[id]/_hooks/useGetInquiry.ts
  src/app/mgc/[id]/_hooks/useIsLikeMGC.ts
  src/app/mgc/[id]/_hooks/useLikeMGC.ts
  src/app/mgc/[id]/_hooks/usePatchInquiry.ts
  src/app/mypage/(sub-page)/change-my-info/_hooks/useChangeMyInfo.ts
Labels: Feat, Modify

#166 [#165] 지도 컴포넌트 리팩토링한 사항 모각코 생성 지도에 반영
  public/mgc_marker.svg
  src/app/(home)/_components/HomeMapContent.tsx
  src/app/(home)/_components/HomeMapViewer.tsx
  src/app/(home)/_components/ThunderModal/MGCMap.tsx
  src/app/(home)/_components/ThunderModal/ThunderModalContent.tsx
  src/app/(home)/page.tsx
  src/app/_components/Map/ClustererProvider.tsx
  src/app/_components/Map/GeocoderProvider.tsx
  src/app/_components/Map/MGCMap.tsx
  src/app/_components/Map/Map.tsx
  src/app/_components/Map/MapLoaderProvider.tsx
  src/app/_components/Map/MapProvider.tsx
  src/app/_components/Map/MapViewer.tsx
  src/app/_components/Map/Marker.tsx
  src/app/_components/Map/Markers.tsx
  src/app/_components/MapCustomControl.tsx
  src/app/_components/infoWindow/InfoWindow.tsx
  src/app/create/_components/CreateMGCMapContent.tsx
  src/app/create/_components/CreateMGCMapViewer.tsx
  src/app/create/_components/MGCMap.tsx
  src/app/create/_components/RequiredFields.tsx
  src/app/layout.tsx
  src/hooks/useChangeMapCenter.ts
  src/hooks/useGetAddressByCoordinates.ts
Labels: Refactor
